language: csharp
jobs:
  include:
    - os: linux
      dotnet: 3.0.100
      mono: none
    - os: osx
      osx_image: xcode11
      dotnet: 3.0.100
      mono: none
sudo: false  # use the new container-based Travis infrastructure
script:
  - dotnet restore ./src/Vlingo.Symbio.Ado.sln;
    dotnet build ./src/Vlingo.Symbio.Ado.sln;
    dotnet test ./src/Vlingo.Symbio.Ado.Tests/Vlingo.Symbio.Ado.Tests.csproj;

notifications:
  slack: vlingo-platform-net:kwiEEBuUpRnz2rYYYstTBpXr